<?php

namespace Botflow\Helpers;

class JSON
{

    public const CONSOLE = JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT;
    public const LOG = JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE;
}
